#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Sep 19, 2021 03:47:41 PM -03  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import about_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = about_simplecrypt_window (root)
    about_support.init(root, top)
    root.mainloop()

w = None
def create_about_simplecrypt_window(rt, *args, **kwargs):
    '''Starting point when module is imported by another module.
       Correct form of call: 'create_about_simplecrypt_window(root, *args, **kwargs)' .'''
    global w, w_win, root
    #rt = root
    root = rt
    w = tk.Toplevel (root)
    top = about_simplecrypt_window (w)
    about_support.init(w, top, *args, **kwargs)
    return (w, top)

def destroy_about_simplecrypt_window():
    global w
    w.destroy()
    w = None

class about_simplecrypt_window:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("390x190+447+212")
        top.minsize(1, 1)
        top.maxsize(1351, 738)
        top.resizable(1,  1)
        top.title("About")
        top.configure(highlightcolor="black")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.128, rely=0.105, height=31, width=289)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(font="-family {DejaVu Sans} -size 23")
        self.Label1.configure(text='''Simple Crypt Tool''')

        self.Labelframe1 = tk.LabelFrame(top)
        self.Labelframe1.place(relx=0.026, rely=0.316, relheight=0.447
                , relwidth=0.949)
        self.Labelframe1.configure(relief='groove')

        self.Label2 = tk.Label(self.Labelframe1)
        self.Label2.place(relx=0.027, rely=0.118, height=72, width=351
                , bordermode='ignore')
        self.Label2.configure(activebackground="#f9f9f9")
        self.Label2.configure(text='''A very simple Crypt/Decrypt Tool, using pyAesCrypt
 library''')

        self.Label3 = tk.Label(top)
        self.Label3.place(relx=0.077, rely=0.789, height=31, width=349)
        self.Label3.configure(activebackground="#f9f9f9")
        self.Label3.configure(cursor="hand2")
        self.Label3.configure(foreground="#140dd8")
        self.Label3.configure(text='''https://github.com/pedropamn/simplecrypt''')
        self.Label3.bind('<Button-1>',lambda e:about_support.open_url())

if __name__ == '__main__':
    vp_start_gui()





