#############################################################################
# Generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#  Sep 19, 2021 03:47:40 PM -03  platform: Linux
set vTcl(timestamp) ""
if {![info exists vTcl(borrow)]} {
    tk_messageBox -title Error -message  "You must open project files from within PAGE."
    exit}


if {!$vTcl(borrow) && !$vTcl(template)} {

set vTcl(actual_gui_font_dft_desc)  TkDefaultFont
set vTcl(actual_gui_font_dft_name)  TkDefaultFont
set vTcl(actual_gui_font_text_desc)  TkTextFont
set vTcl(actual_gui_font_text_name)  TkTextFont
set vTcl(actual_gui_font_fixed_desc)  TkFixedFont
set vTcl(actual_gui_font_fixed_name)  TkFixedFont
set vTcl(actual_gui_font_menu_desc)  TkMenuFont
set vTcl(actual_gui_font_menu_name)  TkMenuFont
set vTcl(actual_gui_font_tooltip_desc)  TkDefaultFont
set vTcl(actual_gui_font_tooltip_name)  TkDefaultFont
set vTcl(actual_gui_font_treeview_desc)  TkDefaultFont
set vTcl(actual_gui_font_treeview_name)  TkDefaultFont
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(actual_gui_menu_active_fg)  #000000
set vTcl(pr,autoalias) 1
set vTcl(pr,relative_placement) 1
set vTcl(mode) Relative
}




proc vTclWindow.top44 {base} {
    global vTcl
    if {$base == ""} {
        set base .top44
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background $vTcl(actual_gui_bg) -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 390x190+447+212
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1351 738
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "About"
    vTcl:DefineAlias "$top" "about_simplecrypt_window" vTcl:Toplevel:WidgetProc "" 1
    set vTcl(real_top) {}
    vTcl:withBusyCursor {
    label $top.lab45 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) \
        -font {-family {DejaVu Sans} -size 23 -weight normal -slant roman -underline 0 -overstrike 0} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Simple Crypt Tool} 
    vTcl:DefineAlias "$top.lab45" "Label1" vTcl:WidgetProc "about_simplecrypt_window" 1
    labelframe $top.lab47 \
        -foreground black -background $vTcl(actual_gui_bg) -height 85 \
        -highlightcolor black -width 370 
    vTcl:DefineAlias "$top.lab47" "Labelframe1" vTcl:WidgetProc "about_simplecrypt_window" 1
    set site_3_0 $top.lab47
    label $site_3_0.lab48 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -foreground $vTcl(actual_gui_fg) \
        -highlightcolor black \
        -text {A very simple Crypt/Decrypt Tool, using pyAesCrypt
 library} 
    vTcl:DefineAlias "$site_3_0.lab48" "Label2" vTcl:WidgetProc "about_simplecrypt_window" 1
    place $site_3_0.lab48 \
        -in $site_3_0 -x 0 -relx 0.027 -y 0 -rely 0.118 -width 0 \
        -relwidth 0.949 -height 0 -relheight 0.847 -anchor nw \
        -bordermode ignore 
    label $top.lab50 \
        -activebackground #f9f9f9 -activeforeground black \
        -background $vTcl(actual_gui_bg) -cursor hand2 -foreground #140dd8 \
        -highlightcolor black -text https://github.com/pedropamn/simplecrypt 
    vTcl:DefineAlias "$top.lab50" "Label3" vTcl:WidgetProc "about_simplecrypt_window" 1
    bind $top.lab50 <Button-1> {
        lambda e: open_url()
    }
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab45 \
        -in $top -x 0 -relx 0.128 -y 0 -rely 0.105 -width 0 -relwidth 0.741 \
        -height 0 -relheight 0.163 -anchor nw -bordermode ignore 
    place $top.lab47 \
        -in $top -x 0 -relx 0.026 -y 0 -rely 0.316 -width 0 -relwidth 0.949 \
        -height 0 -relheight 0.447 -anchor nw -bordermode ignore 
    place $top.lab50 \
        -in $top -x 0 -relx 0.077 -y 0 -rely 0.789 -width 0 -relwidth 0.895 \
        -height 0 -relheight 0.163 -anchor nw -bordermode ignore 
    } ;# end vTcl:withBusyCursor 

    vTcl:FireEvent $base <<Ready>>
}



set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top44 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

