#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 6.2
#  in conjunction with Tcl version 8.6
#    Sep 16, 2021 04:28:12 PM -03  platform: Linux

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    top_level.destroy()
    top_level = None

#Select file to Crypt/Decrypt
def click_on_select_file_btn():
    
    #Enable (if readonly)
    w.filepath.config(state="normal")
    
    from tkinter.filedialog import askopenfilename
    fullpath = askopenfilename() #file path is sstored in this variable
    
    #Insert the filepath into text bar
    w.filepath.delete(0, "end")
    w.filepath.insert(0, fullpath)
    
    #Set ReadyOnly
    w.filepath.config(state="readonly")

def click_on_crypt_button():
    
    #Check if path and password fields are filled
    path = w.filepath.get()
    password = w.password.get()    
    from tkinter import messagebox
    if path == "" or password == '':        
        messagebox.showinfo("Ops", "Fill all fields")
    else:
        import simplecrypt
        c = simplecrypt.crypt(password, path)
        if c == True:
            messagebox.showinfo("Yah", "Done!")
            
            #Enable
            w.filepath.config(state="normal")
            
            #Clear
            w.filepath.delete(0, "end")
            w.password.delete(0, "end")
            
            
        else:
            messagebox.showinfo("Ops", "Error. Check the file path and write permissions")

def click_on_decrypt_button():
    
    #Check if path and password fields are filled
    path = w.filepath.get()
    password = w.password.get()    
    from tkinter import messagebox
    
    if path == "" or password == '':        
        messagebox.showinfo("Ops", "Fill all fields")
    else:
        import simplecrypt
        c = simplecrypt.decrypt(password, path)
        if c == True:
            messagebox.showinfo("Yah", "Done!")
            
            #Enable
            w.filepath.config(state="normal")
            
            #Clear
            w.filepath.delete(0, "end")
            w.password.delete(0, "end")
            
            
        else:
            messagebox.showinfo("Ops", "Error. Check if password is correct")
 
def about():
    import about
    about.vp_start_gui()

if __name__ == '__main__':
    import main
    main.vp_start_gui()
    
    





