# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_aboutDialog(object):
    def setupUi(self, aboutDialog):
        aboutDialog.setObjectName("aboutDialog")
        aboutDialog.resize(400, 331)
        self.label = QtWidgets.QLabel(aboutDialog)
        self.label.setGeometry(QtCore.QRect(60, 0, 71, 101))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/newPrefix/padlock.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(aboutDialog)
        self.label_2.setGeometry(QtCore.QRect(110, 0, 251, 101))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(aboutDialog)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 381, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(aboutDialog)
        self.label_4.setGeometry(QtCore.QRect(210, 70, 67, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(aboutDialog)
        self.label_5.setGeometry(QtCore.QRect(160, 140, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(aboutDialog)
        self.label_6.setGeometry(QtCore.QRect(80, 140, 51, 41))
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/newPrefix/pnlogo.png"))
        self.label_6.setObjectName("label_6")
        self.websiteLink = QtWidgets.QLabel(aboutDialog)
        self.websiteLink.setGeometry(QtCore.QRect(90, 300, 251, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(True)
        self.websiteLink.setFont(font)
        self.websiteLink.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.websiteLink.setOpenExternalLinks(False)
        self.websiteLink.setObjectName("websiteLink")
        self.label_8 = QtWidgets.QLabel(aboutDialog)
        self.label_8.setGeometry(QtCore.QRect(80, 190, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(":/newPrefix/github.png"))
        self.label_8.setObjectName("label_8")
        self.githubProjectLink = QtWidgets.QLabel(aboutDialog)
        self.githubProjectLink.setGeometry(QtCore.QRect(160, 190, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(True)
        self.githubProjectLink.setFont(font)
        self.githubProjectLink.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.githubProjectLink.setObjectName("githubProjectLink")
        self.githubProfileLink = QtWidgets.QLabel(aboutDialog)
        self.githubProfileLink.setGeometry(QtCore.QRect(100, 280, 251, 17))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setUnderline(True)
        self.githubProfileLink.setFont(font)
        self.githubProfileLink.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.githubProfileLink.setOpenExternalLinks(False)
        self.githubProfileLink.setObjectName("githubProfileLink")

        self.retranslateUi(aboutDialog)
        QtCore.QMetaObject.connectSlotsByName(aboutDialog)

    def retranslateUi(self, aboutDialog):
        _translate = QtCore.QCoreApplication.translate
        aboutDialog.setWindowTitle(_translate("aboutDialog", "About SimpleCrypt"))
        self.label_2.setText(_translate("aboutDialog", "SIMPLECRYPT"))
        self.label_3.setText(_translate("aboutDialog", "A simple encryption tool to keep your files private"))
        self.label_4.setText(_translate("aboutDialog", "v.2.0"))
        self.label_5.setText(_translate("aboutDialog", "Developed by Pedro Neto"))
        self.websiteLink.setText(_translate("aboutDialog", "https://www.pedronetoweb.com.br"))
        self.githubProjectLink.setText(_translate("aboutDialog", "Available on Github"))
        self.githubProfileLink.setText(_translate("aboutDialog", "https://github.com/pedropamn"))
#import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    aboutDialog = QtWidgets.QDialog()
    ui = Ui_aboutDialog()
    ui.setupUi(aboutDialog)
    aboutDialog.show()
    sys.exit(app.exec_())
