# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(489, 374)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.choose_btn = QtWidgets.QPushButton(self.centralwidget)
        self.choose_btn.setGeometry(QtCore.QRect(320, 120, 89, 41))
        self.choose_btn.setObjectName("choose_btn")
        self.fullfilepath = QtWidgets.QLineEdit(self.centralwidget)
        self.fullfilepath.setGeometry(QtCore.QRect(80, 120, 211, 41))
        self.fullfilepath.setObjectName("fullfilepath")
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(80, 190, 331, 41))
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 170, 67, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 100, 67, 17))
        self.label_2.setObjectName("label_2")
        self.btn_decrypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_decrypt.setGeometry(QtCore.QRect(260, 250, 121, 71))
        self.btn_decrypt.setObjectName("btn_decrypt")
        self.btn_crypt = QtWidgets.QPushButton(self.centralwidget)
        self.btn_crypt.setGeometry(QtCore.QRect(110, 250, 121, 71))
        self.btn_crypt.setObjectName("btn_crypt")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(180, 40, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_title.setFont(font)
        self.label_title.setObjectName("label_title")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 30, 67, 51))
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/newPrefix/padlock.png"))
        self.label_3.setObjectName("label_3")
        self.eye = QtWidgets.QLabel(self.centralwidget)
        self.eye.setGeometry(QtCore.QRect(420, 190, 51, 31))
        self.eye.setText("")
        self.eye.setPixmap(QtGui.QPixmap(":/newPrefix/eye.png"))
        self.eye.setObjectName("eye")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 489, 22))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.info = QtWidgets.QAction(MainWindow)
        self.info.setObjectName("info")
        self.menuAbout.addAction(self.info)
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SimpleCrypt"))
        self.choose_btn.setText(_translate("MainWindow", "Choose..."))
        self.label.setText(_translate("MainWindow", "Password"))
        self.label_2.setText(_translate("MainWindow", "File Path"))
        self.btn_decrypt.setText(_translate("MainWindow", "Decrypt"))
        self.btn_crypt.setText(_translate("MainWindow", "Crypt"))
        self.label_title.setText(_translate("MainWindow", "SIMPLECRYPT"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.info.setText(_translate("MainWindow", "Info"))
#import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
